### What we are actually going to do
Three things in order:

Download GloVe vectors that were pretrained on Wikipedia + Gigaword (6 billion words) — the 50-dimensional version. These are vectors that someone else already trained, so you get the benefit of massive training data without training anything yourself.


Run similarity queries — give it two words and get back a number between -1 and 1 telling you how similar they are in vector space. You will run pairs that should be similar and pairs that should be distant and verify the scores make intuitive sense.


Run arithmetic — the famous king - man + woman = queen example. You give it positive words and negative words, and it finds the word whose vector is closest to the result of that arithmetic.

## Loading Pre-trained model

In [ ]:
from gensim.downloader import load
model = load("glove-wiki-gigaword-50") 

## Exploring the model

In [5]:
# how many words are in this vocabulary?    answer : (400000, 50) -> 400000 words, each having a 50 dim vector.
model.vectors.shape 

(400000, 50)

In [ ]:
# What does the actual vector for a word look like — what shape is it, what are the numbers?
# answer : the vector is of a shape (50,) and has 50 nums, ech representing the word in a 50 dim space.
model.vectors[3]
# model.vectors[3].shape  # (50,)

array([ 0.70853  ,  0.57088  , -0.4716   ,  0.18048  ,  0.54449  ,
        0.72603  ,  0.18157  , -0.52393  ,  0.10381  , -0.17566  ,
        0.078852 , -0.36216  , -0.11829  , -0.83336  ,  0.11917  ,
       -0.16605  ,  0.061555 , -0.012719 , -0.56623  ,  0.013616 ,
        0.22851  , -0.14396  , -0.067549 , -0.38157  , -0.23698  ,
       -1.7037   , -0.86692  , -0.26704  , -0.2589   ,  0.1767   ,
        3.8676   , -0.1613   , -0.13273  , -0.68881  ,  0.18444  ,
        0.0052464, -0.33874  , -0.078956 ,  0.24185  ,  0.36576  ,
       -0.34727  ,  0.28483  ,  0.075693 , -0.062178 , -0.38988  ,
        0.22902  , -0.21617  , -0.22562  , -0.093918 , -0.80375  ],
      dtype=float32)

In [15]:
model["abc"]

array([ 0.12305  ,  0.1083   ,  0.40415  ,  1.0219   ,  0.085337 ,
        0.62058  , -1.3059   , -0.48724  , -0.3831   , -0.4161   ,
       -0.27984  ,  0.0081618, -0.53566  ,  0.90207  ,  0.86023  ,
        0.50814  , -0.91101  ,  0.55604  , -0.7489   ,  0.57367  ,
        1.0255   ,  1.0432   ,  1.0198   ,  0.65705  , -0.28796  ,
       -0.66948  , -0.56255  ,  0.34756  , -0.014375 , -0.23668  ,
        1.7116   ,  0.84186  ,  0.50027  , -0.7338   , -0.53338  ,
       -0.20271  ,  0.028297 , -0.56163  , -0.54903  , -0.80044  ,
        0.083786 ,  0.36422  , -1.1859   , -0.3878   , -1.0772   ,
       -0.064881 , -0.50498  ,  0.56149  , -0.26193  ,  1.7838   ],
      dtype=float32)

In [ ]:
# What happens when you ask for a word that isn't in the vocabulary
# it returs error saying : KeyError: "Key 'Madiha' not present"
model["Madiha"] 


In [18]:
model.similarity("king", "queen")

np.float32(0.7839043)

In [19]:
model.similarity("man","donkey")

np.float32(0.34654838)

In [20]:
model.similarity("doctor", "nurse")

np.float32(0.79774976)

In [21]:
model.similarity("doctor","hospital")

np.float32(0.6723805)

In [24]:
model.similarity("woman","actor")

np.float32(0.5357743)

In [25]:
model.similarity("king","woman")

np.float32(0.41133785)

In [27]:
model.most_similar("king", topn=10)

[('prince', 0.8236179351806641),
 ('queen', 0.7839043140411377),
 ('ii', 0.7746230363845825),
 ('emperor', 0.7736247777938843),
 ('son', 0.766719400882721),
 ('uncle', 0.7627150416374207),
 ('kingdom', 0.7542160749435425),
 ('throne', 0.7539913654327393),
 ('brother', 0.7492411136627197),
 ('ruler', 0.7434253692626953)]

In [28]:
model.most_similar("doctor", topn=5)

[('nurse', 0.7977497577667236),
 ('physician', 0.7965211272239685),
 ('patient', 0.7611691951751709),
 ('child', 0.7558937668800354),
 ('teacher', 0.7538284063339233)]

In [29]:
model.most_similar("hospital", topn=5)

[('clinic', 0.8607155084609985),
 ('medical', 0.7800323963165283),
 ('hospitals', 0.776480495929718),
 ('nursing', 0.7499141097068787),
 ('psychiatric', 0.7392368316650391)]

In [31]:
model.similar_by_vector("king", topn=10) 

[('prince', 0.8236179351806641),
 ('queen', 0.7839043140411377),
 ('ii', 0.7746230363845825),
 ('emperor', 0.7736247777938843),
 ('son', 0.766719400882721),
 ('uncle', 0.7627150416374207),
 ('kingdom', 0.7542160749435425),
 ('throne', 0.7539913654327393),
 ('brother', 0.7492411136627197),
 ('ruler', 0.7434253692626953)]

In [4]:
model.similarity("lahore","karachi")

np.float32(0.89453053)

In [5]:
model.similarity("pakistan","india")

np.float32(0.8529724)

In [ ]:
#model.similarity("pakistan","china")   # np.float32(0.5725608)
model.similarity("pakistan","afghanistan")   # np.float32(0.7849665)

np.float32(0.7849665)

In [10]:
# checking king-man+woman
model.most_similar(positive=["king","woman"],negative=["man"])

[('queen', 0.8523604273796082),
 ('throne', 0.7664334177970886),
 ('prince', 0.7592144012451172),
 ('daughter', 0.7473883628845215),
 ('elizabeth', 0.7460219860076904),
 ('princess', 0.7424570322036743),
 ('kingdom', 0.7337412238121033),
 ('monarch', 0.721449077129364),
 ('eldest', 0.7184861898422241),
 ('widow', 0.7099431157112122)]

In [11]:
model.most_similar(positive=["islamabad","france"],negative=["pakistan"], topn=5)

[('paris', 0.8538225293159485),
 ('brussels', 0.791949987411499),
 ('strasbourg', 0.7513938546180725),
 ('prohertrib', 0.7511953711509705),
 ('belgium', 0.7029594779014587)]

In [19]:
model.similarity("biryani","shirt")

np.float32(0.025127105)

In [20]:
model.most_similar("doctor")

[('nurse', 0.7977497577667236),
 ('physician', 0.7965211272239685),
 ('patient', 0.7611691951751709),
 ('child', 0.7558937668800354),
 ('teacher', 0.7538284063339233),
 ('surgeon', 0.747907280921936),
 ('psychiatrist', 0.7422093749046326),
 ('doctors', 0.7393609285354614),
 ('father', 0.733410656452179),
 ('mother', 0.728441059589386)]

In [21]:
model.most_similar("university")

[('college', 0.874463677406311),
 ('harvard', 0.8710561394691467),
 ('yale', 0.8566808104515076),
 ('graduate', 0.8552882671356201),
 ('institute', 0.8483645915985107),
 ('professor', 0.8417032361030579),
 ('school', 0.8261534571647644),
 ('faculty', 0.8257830142974854),
 ('graduated', 0.8143773078918457),
 ('academy', 0.8103663921356201)]

In [22]:
model.most_similar("pakistan")

[('pakistani', 0.8867005109786987),
 ('india', 0.8529722690582275),
 ('islamabad', 0.8098275065422058),
 ('bangladesh', 0.8045402765274048),
 ('lanka', 0.798639714717865),
 ('afghanistan', 0.7849665284156799),
 ('sri', 0.7811645269393921),
 ('kashmir', 0.7688103318214417),
 ('egypt', 0.7682687044143677),
 ('afghan', 0.7661849856376648)]

In [ ]:
model.similarity("😂","😘")

In [ ]:
model["Ḁ"]

In [34]:
model["pakistan"]

array([ 0.093731, -0.76398 ,  0.33058 ,  0.56553 ,  0.34119 , -0.43292 ,
        0.47741 ,  0.2661  ,  1.1704  , -0.54634 , -0.16965 , -0.50994 ,
       -0.86457 , -0.67518 , -0.38377 ,  1.1203  ,  0.62431 ,  0.065409,
       -0.12632 ,  1.3     ,  0.24576 ,  1.0203  ,  0.9235  ,  0.41756 ,
        0.29078 , -2.083   ,  0.4507  , -0.44789 , -0.3796  ,  0.48155 ,
        2.8687  ,  0.56244 , -0.087388,  0.57662 ,  0.97655 ,  0.45718 ,
       -0.16975 , -0.43693 , -1.5763  ,  0.19571 , -0.52565 ,  0.66193 ,
       -0.13605 , -0.52883 ,  0.37579 ,  1.0104  , -0.7011  ,  1.2532  ,
       -0.10438 , -1.348   ], dtype=float32)

In [ ]:
# one thing I noticed is that the model has all words starting with lowercase, if i try to write a similar word starting with uppercase, it  gives an error.
# there are no vectors for emojis, so it means that the model was trained on a corpus that did not contain emojis, so it has no way to represent them in the vector space.
# the model doesn't recognize roman urdu words very well, niether pure urdu syntax words. 

In [78]:
model.similar_by_word("allah", topn=5)

[('god', 0.7795286774635315),
 ('ubayd', 0.7551976442337036),
 ('almighty', 0.7490494847297668),
 ('allahu', 0.7256568670272827),
 ('fuck', 0.7069987058639526)]

In [84]:
model.similar_by_word("sardi", topn=10)

[('boulud', 0.6872904300689697),
 ('babbo', 0.681520402431488),
 ('kastrup', 0.6662007570266724),
 ('anta', 0.6529150605201721),
 ('citarella', 0.6517358422279358),
 ('batali', 0.6409454941749573),
 ('landesman', 0.6406360864639282),
 ('lederman', 0.6397050023078918),
 ('zabar', 0.6393812298774719),
 ('rijksmuseum', 0.6366585493087769)]

### An Insight I got

As GloVe calculates vector similarity based on word co-occurrence, I discovered a highly problematic association: the sacred word 'Allah' shares a 70% similarity score with a severe profanity (Na'uzubillah). This reflects how malicious data and deliberate disrespect in the training corpus introduces severe biases into embeddings. Consequently, if this model were deployed in a next-word prediction system, it could catastrophically suggest highly offensive terms in the top recommendations.